// agent-harness/ui/src/lib/components/ui/select.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLSelectAttributes } from "svelte/elements";

  interface Option {
    value: string;
    label: string;
  }

  interface Props extends HTMLSelectAttributes {
    class?: string;
    options: Option[];
    value?: string;
  }

  let { class: className, options, value = $bindable(""), disabled = false, ...rest }: Props = $props();
</script>

<select
  class={cn(
    "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm",
    "ring-offset-background",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
    "disabled:cursor-not-allowed disabled:opacity-50",
    className
  )}
  bind:value
  {disabled}
  {...rest}
>
  {#each options as opt}
    <option value={opt.value}>{opt.label}</option>
  {/each}
</select>

// mvp/src/components/ui/Select.tsx
import { SelectHTMLAttributes, forwardRef } from "react";

interface SelectProps extends SelectHTMLAttributes<HTMLSelectElement> {
  label?: string;
  error?: string;
  options: { value: string; label: string }[];
  placeholder?: string;
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(
  ({ label, error, options, placeholder, className = "", id, ...props }, ref) => {
    const selectId = id || label?.toLowerCase().replace(/\s+/g, "-");
    return (
      <div className="space-y-1.5">
        {label && (
          <label htmlFor={selectId} className="block text-sm font-medium text-text">
            {label}
          </label>
        )}
        <select
          ref={ref}
          id={selectId}
          className={`w-full rounded-lg border px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-colors ${
            error ? "border-danger" : "border-border"
          } ${className}`}
          {...props}
        >
          {placeholder && (
            <option value="" disabled>
              {placeholder}
            </option>
          )}
          {options.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
        {error && <p className="text-sm text-danger">{error}</p>}
      </div>
    );
  },
);

Select.displayName = "Select";
