// ui/src/lib/components/agent/AgentNav.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  interface Props {
    agentName: string;
    activePath: string;
  }

  let { agentName, activePath }: Props = $props();

  const tabs = [
    { label: "Chat", href: (n: string) => `/chat/${n}`, match: "/chat/" },
    { label: "Settings", href: (n: string) => `/agent/${n}/settings`, match: "/settings" },
    { label: "Tests", href: (n: string) => `/agent/${n}/tests`, match: "/tests" },
    { label: "Activity", href: (n: string) => `/agent/${n}/activity`, match: "/activity" },
    { label: "Knowledge", href: (n: string) => `/agent/${n}/knowledge`, match: "/knowledge" },
    { label: "Skills", href: (n: string) => `/agent/${n}/skills`, match: "/skills" },
    { label: "Files", href: (n: string) => `/agent/${n}/workspace`, match: "/workspace" },
    { label: "Channels", href: (n: string) => `/agent/${n}/channels`, match: "/channels" },
    { label: "Voice", href: (n: string) => `/agent/${n}/voice`, match: "/voice" },
  ];

  function isActive(match: string): boolean {
    if (match === "/chat/") return activePath.startsWith("/chat/");
    return activePath.endsWith(match);
  }
</script>

<nav class="sticky top-0 z-10 w-full bg-background shadow-sm">
  <div class="flex items-center px-4 lg:px-6">
    <span class="mr-4 shrink-0 text-sm font-semibold text-foreground">{agentName}</span>
    <div class="scrollbar-hide flex flex-1 overflow-x-auto">
      {#each tabs as tab}
        <a
          href={tab.href(agentName)}
          class={cn(
            "shrink-0 whitespace-nowrap border-b-2 px-3 py-2.5 text-[13px] font-medium transition-colors",
            isActive(tab.match)
              ? "border-primary text-foreground"
              : "border-transparent text-muted-foreground hover:text-foreground"
          )}
        >
          {tab.label}
        </a>
      {/each}
    </div>
  </div>
</nav>

// mvp/src/components/AgentNav.tsx
import { useNavigate, useLocation, useParams } from "react-router-dom";
import { ArrowLeft, Play, GitBranch, FlaskConical, BookOpen, Phone, ShoppingBag, Share2, Lightbulb, Settings, BarChart3, Bot } from "lucide-react";
import { agentPathSegment } from "../lib/agent-path";

const tabs = [
  { path: "activity", icon: BarChart3, label: "Activity" },
  { path: "play", icon: Play, label: "Test" },
  { path: "flow", icon: GitBranch, label: "Flow" },
  { path: "tests", icon: FlaskConical, label: "Evals" },
  { path: "knowledge", icon: BookOpen, label: "Knowledge" },
  { path: "voice", icon: Phone, label: "Voice" },
  { path: "integrations", icon: ShoppingBag, label: "Integrations" },
  { path: "channels", icon: Share2, label: "Channels" },
  { path: "insights", icon: Lightbulb, label: "Insights" },
  { path: "manager", icon: Bot, label: "Manager" },
  { path: "settings", icon: Settings, label: "Settings" },
];

interface AgentNavProps {
  agentName: string;
  children?: React.ReactNode; // page-specific action buttons
}

export function AgentNav({ agentName, children }: AgentNavProps) {
  const navigate = useNavigate();
  const { id } = useParams();
  const location = useLocation();
  const currentPath = location.pathname.split("/").pop() || "";
  const pathSeg = id ? agentPathSegment(id) : agentPathSegment(agentName);

  return (
    <div className="mb-6">
      {/* Breadcrumb row */}
      <div className="flex items-center gap-3 mb-3">
        <button type="button" onClick={() => navigate("/")} className="p-1.5 rounded-lg hover:bg-surface-alt text-text-secondary">
          <ArrowLeft size={18} />
        </button>
        <div className="flex items-center gap-1.5 text-sm">
          <button type="button" onClick={() => navigate("/")} className="text-text-muted hover:text-primary transition-colors">Dashboard</button>
          <span className="text-text-muted">/</span>
          <button type="button" onClick={() => navigate(`/agents/${pathSeg}/activity`)} className="text-text-muted hover:text-primary transition-colors">{agentName}</button>
          <span className="text-text-muted">/</span>
          <span className="font-medium text-text capitalize">{tabs.find((t) => t.path === currentPath)?.label || currentPath}</span>
        </div>
        {children && <div className="ml-auto flex gap-2">{children}</div>}
      </div>

      {/* Tab nav */}
      <div className="flex gap-1 overflow-x-auto border-b border-border">
        {tabs.map((tab) => {
          const active = currentPath === tab.path;
          return (
            <button
              key={tab.path}
              onClick={() => navigate(`/agents/${pathSeg}/${tab.path}`)}
              className={`flex items-center gap-1.5 px-3 py-2 text-xs font-medium border-b-2 whitespace-nowrap transition-all duration-200 ${
                active
                  ? "border-primary text-primary"
                  : "border-transparent text-text-secondary hover:text-text hover:border-gray-300"
              }`}
            >
              <tab.icon size={14} />
              {tab.label}
            </button>
          );
        })}
      </div>
    </div>
  );
}
