// ui/src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { authStore } from "$lib/stores/auth.svelte";
  import { agentStore } from "$lib/stores/agents.svelte";
  import { api } from "$lib/services/api";
  import Button from "$lib/components/ui/button.svelte";
  import Input from "$lib/components/ui/input.svelte";

  let mode = $state<"login" | "signup">("login");

  // Login fields
  let email = $state("");
  let password = $state("");
  let error = $state("");
  let submitting = $state(false);

  // Signup fields
  let signupName = $state("");
  let signupEmail = $state("");
  let signupPassword = $state("");
  let signupConfirm = $state("");
  let inviteCode = $state("");

  async function handleLogin(e: SubmitEvent) {
    e.preventDefault();
    error = "";
    submitting = true;

    try {
      await authStore.login(email, password);
      await agentStore.fetchAgents();
      goto("/");
    } catch (err: unknown) {
      error = err instanceof Error ? err.message : "Login failed";
    } finally {
      submitting = false;
    }
  }

  async function handleSignup(e: SubmitEvent) {
    e.preventDefault();
    error = "";

    if (signupPassword !== signupConfirm) {
      error = "Passwords do not match";
      return;
    }
    if (signupPassword.length < 8) {
      error = "Password must be at least 8 characters";
      return;
    }

    submitting = true;
    try {
      await api.signup(signupName, signupEmail, signupPassword, inviteCode || undefined);
      // Auto-login after signup
      await authStore.login(signupEmail, signupPassword);
      await agentStore.fetchAgents();
      goto("/");
    } catch (err: unknown) {
      error = err instanceof Error ? err.message : "Signup failed";
    } finally {
      submitting = false;
    }
  }
</script>

<div class="flex min-h-dvh items-center justify-center p-4">
  <div class="w-full max-w-sm space-y-6">
    <div class="text-center">
      <h1 class="text-3xl font-bold text-primary">OneShots</h1>
      <p class="mt-2 text-sm text-muted-foreground">
        {mode === "login" ? "Sign in to your account" : "Create your account"}
      </p>
    </div>

    {#if mode === "login"}
      <form onsubmit={handleLogin} class="space-y-4">
        {#if error}
          <div class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </div>
        {/if}

        <div class="space-y-2">
          <label for="email" class="text-sm font-medium">Email</label>
          <Input
            id="email"
            type="email"
            placeholder="you@example.com"
            bind:value={email}
            required
            autocomplete="email"
          />
        </div>

        <div class="space-y-2">
          <label for="password" class="text-sm font-medium">Password</label>
          <Input
            id="password"
            type="password"
            placeholder="Password"
            bind:value={password}
            required
            autocomplete="current-password"
          />
        </div>

        <Button type="submit" class="w-full" disabled={submitting}>
          {#if submitting}
            Signing in...
          {:else}
            Sign in
          {/if}
        </Button>
      </form>

      <p class="text-center text-sm text-muted-foreground">
        Don't have an account?
        <button
          type="button"
          class="font-medium text-primary transition-colors hover:text-primary/80"
          onclick={() => { mode = "signup"; error = ""; }}
        >
          Sign up
        </button>
      </p>
    {:else}
      <form onsubmit={handleSignup} class="space-y-4">
        {#if error}
          <div class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </div>
        {/if}

        <div class="space-y-2">
          <label for="signup-name" class="text-sm font-medium">Name</label>
          <Input
            id="signup-name"
            type="text"
            placeholder="Your name"
            bind:value={signupName}
            required
            autocomplete="name"
          />
        </div>

        <div class="space-y-2">
          <label for="signup-email" class="text-sm font-medium">Email</label>
          <Input
            id="signup-email"
            type="email"
            placeholder="you@example.com"
            bind:value={signupEmail}
            required
            autocomplete="email"
          />
        </div>

        <div class="space-y-2">
          <label for="signup-password" class="text-sm font-medium">Password</label>
          <Input
            id="signup-password"
            type="password"
            placeholder="Min. 8 characters"
            bind:value={signupPassword}
            required
            autocomplete="new-password"
          />
        </div>

        <div class="space-y-2">
          <label for="signup-confirm" class="text-sm font-medium">Confirm Password</label>
          <Input
            id="signup-confirm"
            type="password"
            placeholder="Confirm password"
            bind:value={signupConfirm}
            required
            autocomplete="new-password"
          />
        </div>

        <div class="space-y-2">
          <label for="invite-code" class="text-sm font-medium">
            Invite Code <span class="text-muted-foreground">(optional)</span>
          </label>
          <Input
            id="invite-code"
            type="text"
            placeholder="Invite code"
            bind:value={inviteCode}
          />
        </div>

        <Button type="submit" class="w-full" disabled={submitting}>
          {#if submitting}
            Creating account...
          {:else}
            Sign up
          {/if}
        </Button>
      </form>

      <p class="text-center text-sm text-muted-foreground">
        Already have an account?
        <button
          type="button"
          class="font-medium text-primary transition-colors hover:text-primary/80"
          onclick={() => { mode = "login"; error = ""; }}
        >
          Sign in
        </button>
      </p>
    {/if}
  </div>
</div>

// portal/src/pages/auth/login.tsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../../lib/auth";
import { isClerkMode } from "../../auth/config";

function ClerkLoginPage() {
  // Dynamic import to avoid bundling Clerk when not in Clerk mode
  const [ClerkSignIn, setClerkSignIn] = useState<React.ComponentType<any> | null>(null);

  // Lazy load Clerk SignIn component
  if (!ClerkSignIn) {
    import("@clerk/clerk-react").then((mod) => {
      setClerkSignIn(() => mod.SignIn);
    });
    return (
      <div className="min-h-screen flex items-center justify-center bg-surface-base">
        <div className="text-text-muted text-sm">Loading authentication...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-surface-base p-[var(--space-6)]">
      <div className="flex flex-col items-center gap-[var(--space-6)]">
        {/* Brand */}
        <div className="text-center">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-accent-muted mb-[var(--space-4)]">
            <span className="text-accent font-bold text-[var(--text-xl)]">O</span>
          </div>
          <h1 className="text-[var(--text-xl)] font-bold text-text-primary">
            Sign in to AgentOS
          </h1>
          <p className="mt-[var(--space-2)] text-[var(--text-sm)] text-text-muted">
            Agent infrastructure platform
          </p>
        </div>

        {/* Clerk SignIn component — handles all auth flows */}
        <ClerkSignIn
          appearance={{
            elements: {
              rootBox: "w-full max-w-md",
              card: "bg-surface-raised border border-border-default shadow-panel rounded-xl",
              headerTitle: "text-text-primary",
              headerSubtitle: "text-text-secondary",
              formFieldLabel: "text-text-secondary text-sm",
              formFieldInput:
                "bg-surface-overlay border-border-default text-text-primary rounded-lg",
              formButtonPrimary:
                "bg-accent hover:bg-accent-hover text-white rounded-lg min-h-[var(--touch-target-min)]",
              footerActionLink: "text-accent hover:text-accent-hover",
              identityPreviewEditButton: "text-accent",
              socialButtonsBlockButton:
                "bg-surface-overlay border-border-default text-text-primary hover:bg-surface-hover rounded-lg",
              dividerLine: "bg-border-default",
              dividerText: "text-text-muted",
            },
          }}
          routing="path"
          path="/login"
          signUpUrl="/signup"
          fallbackRedirectUrl="/"
        />
      </div>
    </div>
  );
}

function LocalLoginPage() {
  const { login, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  // Already authenticated — redirect
  if (isAuthenticated) {
    navigate("/", { replace: true });
    return null;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      await login(email, password);
      navigate("/", { replace: true });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Sign in failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-surface-base p-[var(--space-6)]">
      <div className="card w-full max-w-md">
        {/* Brand */}
        <div className="text-center mb-[var(--space-8)]">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-accent-muted mb-[var(--space-4)]">
            <span className="text-accent font-bold text-[var(--text-xl)]">O</span>
          </div>
          <h1 className="text-[var(--text-xl)] font-bold text-text-primary">
            Sign in to AgentOS
          </h1>
          <p className="mt-[var(--space-2)] text-[var(--text-sm)] text-text-muted">
            Agent infrastructure platform
          </p>
        </div>

        {/* Error */}
        {error && (
          <div className="mb-[var(--space-4)] p-[var(--space-3)] rounded-lg bg-status-error/10 border border-status-error/20 text-[var(--text-sm)] text-status-error">
            {error}
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-[var(--space-4)]">
          <div>
            <label
              htmlFor="login-email"
              className="block text-[var(--text-sm)] text-text-secondary mb-[var(--space-1)]"
            >
              Email
            </label>
            <input
              id="login-email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@company.com"
              required
              autoComplete="email"
              autoFocus
              minLength={1}
            />
          </div>
          <div>
            <label
              htmlFor="login-password"
              className="block text-[var(--text-sm)] text-text-secondary mb-[var(--space-1)]"
            >
              Password
            </label>
            <input
              id="login-password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter your password"
              required
              autoComplete="current-password"
              minLength={8}
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="btn btn-primary w-full min-h-[var(--touch-target-min)]"
          >
            {loading ? "Signing in..." : "Sign in"}
          </button>
        </form>

        {/* Signup link */}
        <p className="text-center mt-[var(--space-6)] text-[var(--text-sm)] text-text-muted">
          Don&apos;t have an account?{" "}
          <Link to="/signup" className="text-accent hover:text-accent-hover transition-colors">
            Sign up
          </Link>
        </p>
      </div>
    </div>
  );
}

export function LoginPage() {
  return isClerkMode() ? <ClerkLoginPage /> : <LocalLoginPage />;
}
